### PR TITLE
Bugfix - #3968 - wA WordList to not scroll when moving words

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes #3968
- Dependencies (kind of, just so you don't see an error in console): https://github.com/unfoldingWord-dev/translationCore/pull/4123

#### Please include detailed Test instructions for your pull request:
- Checkout `bugfix-richmahn-3968` in wordAlignment and tC root. Run app. Go to wA of a project. Find a verse that has enough words to make the scroll bar appear in word list. Scroll down in word list. Take a word and move it over to alignment area. Word List should remain where you left it. Move word back. Still stays. Change to another verse and the Word List scrollbar should return to the top.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/30)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `LGTM`
Would be nice to see some comments in the logic for `componentWillRecieveProps` and `componentDidUpdate`

**Comment by mannycolon** [comment]
@richmahn Please increase the test coverage for this PR

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/30)*

**Comment by mannycolon** [comment]
Local Testing: `Pending`
Code Review: `LGTM`

**Comment by richmahn** [comment]
@mannycolon @RoyalSix This one is already ready now.

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r2, 3 of 7 files at r3, 6 of 7 files at r4.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/30)*

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `LGTM`
Waiting on @mannycolon 's `OK`

**Comment by mannycolon** [comment]
Reviewed 1 of 7 files at r3, 3 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/components/WordList/index.js, line 34 at r4](https://beta.reviewable.io/reviews/translationcoreapps/wordalignment/30#-L8Z2Xra7gTHPp64u--g:-L8Z2Xra7gTHPp64u--h:blad3hi) ([raw file](https://github.com/translationcoreapps/wordalignment/blob/6f1313b31a14f211356035ccfd2f2f67b5700232/src/components/WordList/index.js#L34)):*
> ```JavaScript
>     }
>   }
> ```

@richmahn react lifecycle functions should go first and then any other methods follow below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/wordalignment/30)*

**Comment by mannycolon** [comment]
Local Testing: `LGTM`
Code Review: `PENDING REQUESTED CHANGES`

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/30#-:-L8bDb0vCFvpCS2ycA9f:bnfp4nl)*

**Pull request merged**
