### PR TITLE
Basic MAP

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):
related to https://github.com/unfoldingWord-dev/translationCore/issues/2258.
Depends on https://github.com/unfoldingWord-dev/translationCore/pull/4621
- Adds basic MAP

#### Please include detailed Test instructions for your pull request:
Currently we are seeding MAP with saved alignments from the current chapter only (I'm actively adding support for the rest or the book).
- make an alignment in a verse then view another verse with the same source words and watch them be magically suggested!

See the requirements in https://github.com/unfoldingWord-dev/translationCore/issues/2258 for features to test.

#### Standard Test Instructions for PR Review Process:

- [x] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/43)

### CODE REVIEW

**Comment by neutrinog** [comment]
@klappy I just pushed some updates that fixes several bugs with rendering suggestions that split alignments.

**Comment by klappy** [comment]
- Alignment suggestions from previously alignments works as expected.

**Comment by neutrinog** [comment]
* Most of the tests were focused on the logic. We can easily add some tests to cover the UI changes.
* The split alignment is a small corner case where the use has merged two source tokens together but has not aligned any target tokens to it.
  * in Titus 2:13 make sure "to" is aligned with the second "kai"
  * in Titus 2:15 merge the second "kai" with a word beside it and remove any alignments.
  * refresh the suggestions to view the split.

**Comment by neutrinog** [comment]
I have prevented the random merging of Greek phrases. The way I implemented this will also cause merged phrases that are not aligned to be split. However, I think this will be rare from the user standpoint.

To properly avoid messing around with un-aligned phrases I'll need to re-design parts of the rendering algorithm, and given the low likelihood of someone actually encountering it, I'd like to wait until we get some more important features added.

**Comment by PhotoNomad0** [comment]
Local Testing looks good, haven't started code review.  Has merge conflict.

**Comment by neutrinog** [comment]
@PhotoNomad0 fyi this now loads the entire book. So you can check if any verse is finished.

**Comment by PhotoNomad0** [comment]
Reviewed 27 of 39 files at r1, 4 of 7 files at r2, 1 of 1 files at r3, 10 of 11 files at r4, 2 of 4 files at r5, 4 of 4 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @klappy)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/43)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @klappy)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/43#-:-LFg4khYDJ3oCMwDn-bk:bnfp4nl)*

**Pull request merged**
