### PR TITLE
Drag Multiple Target Words

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingWord-dev/translationCore/issues/4354
- Adds support for selecting and dragging multiple target words from the word list.

> NOTE: There is a bug in chromium where PNGs with transparency are rendered with a white background instead of a transparent one while being dragged. See [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=347333). The bug has been fixed, however the version of Chromium currently used in tC (`56`) was released shortly after the fix so it seems it missed that particular fix. In the future we should update electron to get a newer version of Chromium. For example [Electron 2.0.8](https://electronjs.org/releases#2.0.8) contains Chromium `61.0.3163.100`

#### Please include detailed Test instructions for your pull request:
- Click on a word in the word list to select it.
- Select several words
- Drag the selection to an alignment

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/72)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - code coverage drop here

**Comment by PhotoNomad0** [comment]
@neutrinog - it seems to work well overall, but I was doing an alignment in Gal.  When I got to 1:4.  Dragged "the" from a suggested alignment into "τὸ".  Then as I was dragging "will" over, I got a popup that verse had changed and alignments were reset.  Working to see if I can reproduce it, and will post the project if I can.

**Comment by PhotoNomad0** [comment]
Screen shots of activity before alert.

screen shot 2018-08-23 at 10 11 04 am

screen shot 2018-08-23 at 10 11 41 am

**Comment by PhotoNomad0** [comment]
Reproduced the fault again, by clicking reject of the suggestions, then unaligning all the words.  Then clicked on 1:3 and got the message the broken alignments message for 1:4

**Comment by PhotoNomad0** [comment]
Here is the project I am working on: 

[aig_algn_gal_book.zip](https://github.com/translationCoreApps/wordAlignment/files/2315049/aig_algn_gal_book.zip)

I can reproduce the crash by opening project, opening WA tool, then select 1:4.  Starting with first word "τοῦ", I started unaligning words from left to right.  After unaligning the group "τῶν ἁμαρτιῶν". I then split the pair.  Then unaligned the next word "ἡμῶν".  Then clicked on Gal 1:3.  Then I got the alignments broken message.

**Comment by PhotoNomad0** [comment]
Merging this since the problem seems to be in current develop branch.  Kos is opening an issue.

**Comment by cckozie** [comment]
I wrote up the alignments invalidated message problem in #4933

**Pull request merged**
