### PR TITLE
Feature 4791/unalign any primary word and move any primary word to any other alignment

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- canDropPrimaryToken() - removed drop limitation to adjacent alignments
- dragHandler.canDrag() - removed limitation that you can only drag from first or last entry.
- fixed alignments rendering to support discontiguous alignments
- added unit test for discontiguous alignments in render.

#### Please include detailed Test instructions for your pull request:
- here are test builds you can try - see most recent builds in http://tc-builds.door43.org.s3-website-us-west-2.amazonaws.com/build/release-v1.2.0-testing/
- look at the specs in https://github.com/unfoldingword-dev/translationcore/issues/4791.  Open up a project in WA tool and you should be able to do operations in spec 1 to 3 in all sorts of combinations and spec 4 to 5 should stay consistent.  Also should not lose Greek words or see duplicates.  Also keep an eye on console - will see alignment errors displayed if alignments become inconsistent.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/179)

### CODE REVIEW

**Comment by mannycolon** [comment]
FYI - will also need to add `deep-freeze` to the `package.json` on the tC repo in order for it to work.

**Comment by PhotoNomad0** [comment]
Need to add Primary word occurrence number.

**Comment by PhotoNomad0** [comment]
@mannycolon @RoyalSix - build 5162876 (v1.2.0) is ready for testing on http://tc-builds.door43.org.s3-website-us-west-2.amazonaws.com/build/release-v1.2.0-testing/

**Comment by mannycolon** [comment]
Downloading build for local test

**Pull request merged**
