### PR TITLE
Adds localization support

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):

This related to https://github.com/unfoldingWord-dev/translationCore/issues/3891
This utilizes a new [tool HOC](https://github.com/translationCoreApps/tc-tool) that adds locale support to tc apps.

updated dependencies.

other syntax improvements.

#### Please include detailed Test instructions for your pull request:

I couldn't actually find anything in this tool that needed localization.
So just make sure I didn't break the tool!

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/22)

### CODE REVIEW

**Comment by neutrinog** [comment]
btw. there are a bunch of commits because I was developing the interface inline before abstracting it out to it's own library.

**Comment by mannycolon** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/22)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/22#-:-L6IpqRqBDm9AssLwgI6:bnfp4nl)*

**Comment by neutrinog** [comment]
There's a bug in tC core that needs to be fixed before this can be merged.

**Comment by neutrinog** [comment]
This is now ready to go. As a short term fix we installed the required dependencies directly in tC. See https://github.com/unfoldingWord-dev/translationCore/pull/3902

**Comment by PhotoNomad0** [comment]
@neutrinog - So does #3902 need to be merged first?

**Comment by neutrinog** [comment]
@PhotoNomad0 yes! Should have labeled it as such.

Blocked by https://github.com/unfoldingWord-dev/translationCore/pull/3902

**Pull request merged**
