### PR TITLE
Added scripture pane from tc-ui-toolkit

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added scripture pane from `tc-ui-toolkit`

#### Please include detailed Test instructions for your pull request:
- Open the wA tool
- Test the scripture pane 
##### Dependencies 
- https://github.com/translationCoreApps/translationWords/pull/127
- https://github.com/unfoldingWord-dev/translationCore/pull/4594

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/39)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/39)*

**Comment by PhotoNomad0** [comment]
@mannycolon - seeing a lot of untranslated strings when I open up verseEdit

**Comment by PhotoNomad0** [comment]
@mannycolon - also seeing crash when I add a 4th language to pane

**Comment by mannycolon** [comment]
@PhotoNomad0 
All the locale strings on the tools got reset because we moved them out of the different repos and put them all together in the tools.

**Comment by mannycolon** [comment]
@PhotoNomad0 Can you post a screenshot of the error?

**Comment by RoyalSix** [comment]
I am getting `translate is not a function` after clicking a word something on the OG pane

**Comment by RoyalSix** [comment]
And the status bar is missing like how it was in the tW tool

**Comment by mannycolon** [comment]
@RoyalSix Looks like you fix didnt work

**Comment by mannycolon** [comment]
> @mannycolon - seeing a lot of untranslated strings when I open up verseEdit

@PhotoNomad0 This is not part of the scope of this PR. that was somehting that shouldve been brought up in tW rewrite.

**Comment by PhotoNomad0** [comment]
@mannycolon - seeing this when I open verseEdit (I have locale set to English):

screen shot 2018-06-08 at 12 40 06 pm

**Comment by PhotoNomad0** [comment]
@mannycolon - seeing issue that menubar is not shown with Galatians project (see it with Titus project however):

screen shot 2018-06-08 at 12 50 18 pm

**Comment by mannycolon** [comment]
> @mannycolon - also seeing crash when I add a 4th language to pane

@PhotoNomad0 How can i recreate this bug?

**Comment by PhotoNomad0** [comment]
> > @mannycolon - also seeing crash when I add a 4th language to pane
> 
> @PhotoNomad0 How can i recreate this bug?

@mannycolon - Seems to be working now with latest changes.

**Comment by PhotoNomad0** [comment]
@mannycolon - seeing problem with adding languages to SP.  When I add a 4th language, it shows up on SP and I see this reflected in settings.json:

```
    "toolsSettings": {
        "ScripturePane": {
            "currentPaneSettings": [
                {
                    "languageId": "targetLanguage",
                    "bibleId": "targetBible"
                },
                {
                    "languageId": "originalLanguage",
                    "bibleId": "ugnt"
                },
                {
                    "languageId": "en",
                    "bibleId": "udt"
                },
                {
                    "languageId": "en",
                    "bibleId": "ult"
                }
            ]
        }
    },
```

But if i exit the tool and open WA again, it only shows 3 languages in SP.  The 4th language is also stripped out of the settings file:

```
    "toolsSettings": {
        "ScripturePane": {
            "currentPaneSettings": [
                {
                    "languageId": "targetLanguage",
                    "bibleId": "targetBible"
                },
                {
                    "languageId": "originalLanguage",
                    "bibleId": "ugnt"
                },
                {
                    "languageId": "en",
                    "bibleId": "ult"
                }
            ]
        }
    },

```

**Comment by PhotoNomad0** [comment]
> @mannycolon - seeing issue that menubar is not shown with Galatians project (see it with Titus project however):

@mannycolon - this is working now.

**Comment by PhotoNomad0** [comment]
> @mannycolon - seeing this when I open verseEdit (I have locale set to English):

@mannycolon - this is working now, see the button labels.

**Comment by mannycolon** [comment]
@PhotoNomad0 @RoyalSix I think I have made all the necessary changes to address all the bugs/questions/comments

**Comment by RoyalSix** [comment]
Theres a few issues involved in this so not sure where to put this but I don't think the scripture pane should expand like that ?
screen shot 2018-06-08 at 10 49 32 pm

**Comment by mannycolon** [comment]
> Theres a few issues involved in this so not sure where to put this but I don't think the scripture pane should expand like that?

@RoyalSix Actually there is a story to make the scripture pane expand vertically. But I agree it should not expand like that in the word alignment tool. 

I'm making some changes to address that issue.

**Comment by mannycolon** [comment]
@RoyalSix I made changes to improve the layout issues related to the scripture pane

**Comment by RoyalSix** [comment]
`@RoyalSix I made changes to improve the layout issues related to the scripture pane`

This looks fixed now

**Comment by RoyalSix** [comment]
screen shot 2018-06-11 at 9 12 29 am
I'm wondering if the pane is expected to look like this if theres no bibles loaded, as compared to before.
screen shot 2018-06-11 at 9 15 42 am

This may be outside the scope of this PR but it still might need to get fixed.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 3 files at r6, 2 of 4 files at r7, 2 of 2 files at r8.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix and @richmahn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/39#-:-LEjl3pf-bFu8djeQ0Ti:bnfp4nl)*

**Pull request merged**
