### PR TITLE
minor improvements to scripture pane updates

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This contains some minor improvements to parameter passing to support future changes to the ScripturePane. This is required for https://github.com/unfoldingWord-dev/translationCore/issues/2004
- Also fixed alignments grid to scroll properly

#### Please include detailed Test instructions for your pull request:
- make sure the ScripturePane still opens. 

> NOTE: I get errors when opening the scripture pane on my local builds that I don't see in travis builds.
> This is due to some inappropriate usages of `ref`.  You may need to test this along with another PR (will update with link) for the ScripturePane which will contain a fix for this.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/wordalignment/28)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/28)*

**Comment by mannycolon** [comment]
@neutrinog Looks good. Just resolve merge conflicts.

**Comment by neutrinog** [comment]
note to developers. Although this is related to https://github.com/unfoldingWord-dev/translationCore/issues/2004 this PR should not push the issue into review or QA.
This PR is simply a compatibility fix.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/wordalignment/28#-:-L89LHIwl0FnUdd4kIB_:bnfp4nl)*

**Pull request merged**
